### ISSUE TITLE
mattr s $wid fails when window exists on inactive monitor.

### ISSUE THREAD

**Issue by lwilletts** [pockata/mmutils#10]
Hi, I have a listwindows function that can be sourced and works by checking all active windows and their monitors, then grep is used to find only the windows on the given monitor.

```
listwindows() {
    mattr "$1"

    case "$?" in
        0) SCR="$1"     ;;
        *) SCR="$(pfm)" ;;
    esac

    mattr si $(lsw) | grep -F "$SCR" | cut -d\  -f 1
}
```

Unfortunately `mattr s` reports this when a display is not active and produces no further output:

```
mattr: monitor 0x0160000c not active
```

Perhaps, if a window is found on an inactive monitor, mattr simply doesn't produce any output for that window? I often have inactive monitors because I turn them off using ddcutil when not required.

**Comment by pockata** [comment]
Hey @lwilletts, thanks for taking the time to open this issue.

I was able to replicate the behavior you described by moving a couple of
windows to a monitor and then disabling that monitor via xrandr.

> Perhaps, if a window is found on an inactive monitor, mattr simply
> doesn't produce any output for that window? I often have inactive
> monitors because I turn them off using ddcutil when not required.

I wouldn't want to disable error messages by default because that is
useful in some situations (I really need to improve the error message in
here, because it's not really clear what's going on). Also, the reason
the script stops producing output is because `mattr` exits after the
first error.

Perhaps a `-q` parameter to silence the errors and not produce an exit
code would be the best approach here, but it'll require some not so
simple changes to the current codebase to support at least the following
scenarios:

```
$ mattr -q whxy $(pfw)
$ mattr whxy -q $(pfw)
$ mattr -g -q $(pfw)
$ mattr -gq $(pfw)
```

I currently don't have plans to implement it, but will happily review a
PR.

Here's a couple of quick fixes you can implement in your scripts.

You can prevent mattr's exit code from stopping execution by using
`xargs`:
```
$ lsw | xargs -n 1 mattr si 2> /dev/null
```
instead of
```
$ mattr si $(lsw)
```

Or you can move all the windows that are in an inactive monitor to an
active one with something along the lines of: [this script](https://github.com/pockata/dotfiles/blob/a7596c05df0577016e4e02b700fb92effc9d9543/utils/bin/monitors.sh#L35-L43). It runs right
after I make changes to the monitor setup.

**Comment by lwilletts** [comment]
Thanks for the in-depth response firstly. I completely agree that users need good error messages in order to understand what is happening, sometimes it is easy to forget that although *we* know what's going on, others may not. From my brief experience coding phrasing input arguments is always a pain, and there's no easy answers. I think it unrealistic too considering the project scope and time to sort it out for such a minor quibble and as such I'm satisfied and will close this issue.

Your xargs solutions works perfectly for my use case (why do I always forget about it??). For me, swapping the windows to my active monitors is not entirely what I would want as I only often turn the monitor off temporarily, but definitely very useful for plugging in external outputs on a laptop frequently for example!
