### ISSUE TITLE
Mattr: No way to return given wid.

### ISSUE THREAD

**Issue by lwilletts** [pockata/mmutils#3]
In wmutils, `wattr i $(pfw)` simply returns the pfw given. Using `mattr -i $(pfw)` gives only the monitor, which is 1. inconsistent with wmutils precedent 2. means that there is no way to get something like the following output using only one call of mattr:

```
$ for i in $(lsw); do; printf '%s\n' "$(mattr i $i) $i "; done
DisplayPort-1 0x00c00134 
DisplayPort-1 0x00c00019 
DisplayPort-2 0x01e0000a 
DisplayPort-1 0x00c000f1 
DisplayPort-1 0x00c000a6 
HDMI-A-2 0x01400003 
DisplayPort-1 0x00c00028 
DisplayPort-1 0x00c0004c 
DisplayPort-1 0x00c00088 
DisplayPort-1 0x00c00171
```

Fix: Allow `mattr si $(lsw)` to return the above output.

**Comment by pockata** [comment]
Hey, thanks for taking interest in mmutils!

I see where you're coming from with the inconsistency issue. Initially, i modeled mmutils to exactly mimic wmutils, e.g.
```
wattr ixy $(pfw)
# is equivalent to
mattr ixy $(pfm)
```
The two lines are equivalent in the sense that they accept the ID of the object (window and monitor respectively) and return the ID, and the X and Y coordinates of their respective objects.

Later on I decided to add support to `mattr` for getting a monitor via a window ID which caused this inconsistency.

The other path I was considering was to create a separate tool which returns a monitor ID by a window ID - pwm - Print Window's Monitor. This would have been more idiomatic and a bit more unix-y, however I decided against it, because it would have yielded something like `mattr ixy $(pwm "0x....")` and I didn't like the extra program execution. Also, it would still have lead to the same problem.

~~I haven't encountered your use case~~, but I can see how the chainability / piping is broken.
I actually found that a piece of code in my scripts that tries to achieve this. Take a look at this monstrosity - `paste <(lsw | xargs mattr i) <(lsw)` :scream:  It has a `TODO: fix this` above it, so I guess that time has come.

I don't really like the `s` option, because it diverges too much from wmutils, however I cannot think of a better option at this time. I'll sleep on it and probably implement it in a couple of days.

PS. I'm curious what's your use case for this feature?

**Comment by lwilletts** [comment]
If I need all window id's on a given screen e.g. to cycle focus on windows on that screen, plus many other operations on only windows on the given screen i.e. mass close or mass unmap: this example is one way to achieve that:

```
PFW="$(pfw 2> /dev/null || printf '%s\n' "0x00000001")"
SCR=$(mattr i $PFW)

for wid in $(lsw); do
    printf '%s\n' "$(mattr i $wid) $wid"
done | grep "$SCR" | cut -d\  -f 2

0x00c00019
0x00c00046
0x00c00037
```

If mattr had support to return window id's this could be simplified to:

```
PFW="$(pfw 2> /dev/null || printf '%s\n' "0x00000001")"
SCR=$(mattr s $PFW)

mattr i "$SCR"
```

**Comment by pockata** [comment]
I've given it some thought and I can't find a better way, so I'm going with the `s` route.
I've implemented the functionality, I just need to update the docs and man pages and I'll push the changes tomorrow.

**Comment by lwilletts** [comment]
Hiya, great stuff pushing the update but I think there is a bug introduced. Passing `$(lsw)` to mattr only finds the first wid passed then repeats it for the rest of the output:

```
| lsw 
0x02800006
0x04000029
0x01800003
0x00c00a4a
0x00c00a59
0x00c0003c
0x00c00069
0x00c0000a
| mattr i $(lsw)
DisplayPort-2
DisplayPort-1
HDMI-A-2
DisplayPort-1
DisplayPort-1
DisplayPort-1
DisplayPort-1
DisplayPort-1
| mattr si $(lsw)
0x02800006 DisplayPort-2
0x02800006 DisplayPort-1
0x02800006 HDMI-A-2
0x02800006 DisplayPort-1
0x02800006 DisplayPort-1
0x02800006 DisplayPort-1
0x02800006 DisplayPort-1
0x02800006 DisplayPort-1
```

Also I would have thought you would have wanted `mattr i` to return the wid and `mattr s` to return the screen. Alternatively if you still want `mattr i` to return the screen, maybe make the return of the wid be `mattr w`. That's what makes the most sense to me anyhow. Good work nevertheless.

**Comment by pockata** [comment]
Kids, this is why you need automated testing.

Thanks for catching this!
I've pushed a new release which fixes the issue.

> Also I would have thought you would have wanted mattr i to return the wid and mattr s to return the
> screen. Alternatively if you still want mattr i to return the screen, maybe make the return of the wid
> be mattr w. That's what makes the most sense to me anyhow. Good work nevertheless.

In xcb, the monitor is actually referenced by `name`, that's why I chose `n`. `i` was just an alias to make `mmutils` and `wmutils`' options similar. In `wmutils`, `i` references `wid`, however in `mmutils`, `i` references `mid`. 

In my head `s` is the `source input` used to identify the monitor, either a `wid` or a `mid`. 

I've updated the readme and the docs to reference `n` instead of `i` as it seems it might cause confusion. I might consider removing it in the future.

`w` is already used for getting a monitor's width.

Please feel free to open other tickets if you encounter any more issues.
